# Generated by Django 3.2.8 on 2021-10-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
